# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 261)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_info = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_info.setObjectName("pushButton_info")
        self.verticalLayout.addWidget(self.pushButton_info)
        self.pushButton_warn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_warn.setObjectName("pushButton_warn")
        self.verticalLayout.addWidget(self.pushButton_warn)
        self.pushButton_error = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_error.setObjectName("pushButton_error")
        self.verticalLayout.addWidget(self.pushButton_error)
        self.pushButton_question = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_question.setObjectName("pushButton_question")
        self.verticalLayout.addWidget(self.pushButton_question)
        self.pushButton_about = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_about.setObjectName("pushButton_about")
        self.verticalLayout.addWidget(self.pushButton_about)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_info.setText(_translate("MainWindow", "消息框"))
        self.pushButton_warn.setText(_translate("MainWindow", "警告框"))
        self.pushButton_error.setText(_translate("MainWindow", "错误框"))
        self.pushButton_question.setText(_translate("MainWindow", "问题框"))
        self.pushButton_about.setText(_translate("MainWindow", "关于框"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
