# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'borrow_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Borrow_history(object):
    def setupUi(self, Borrow_history):
        Borrow_history.setObjectName("Borrow_history")
        Borrow_history.resize(553, 290)
        self.tableWidget_history = QtWidgets.QTableWidget(Borrow_history)
        self.tableWidget_history.setGeometry(QtCore.QRect(5, 11, 541, 261))
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(0)
        self.tableWidget_history.setRowCount(0)
        self.tableWidget_history.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(Borrow_history)
        QtCore.QMetaObject.connectSlotsByName(Borrow_history)

    def retranslateUi(self, Borrow_history):
        _translate = QtCore.QCoreApplication.translate
        Borrow_history.setWindowTitle(_translate("Borrow_history", "Dialog"))
