# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePwdDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_pwd_dialog(object):
    def setupUi(self, Change_pwd_dialog):
        Change_pwd_dialog.setObjectName("Change_pwd_dialog")
        Change_pwd_dialog.resize(287, 258)
        self.buttonBox = QtWidgets.QDialogButtonBox(Change_pwd_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 190, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.le_old_pwd = QtWidgets.QLineEdit(Change_pwd_dialog)
        self.le_old_pwd.setGeometry(QtCore.QRect(110, 30, 161, 31))
        self.le_old_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.le_old_pwd.setText("")
        self.le_old_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_old_pwd.setObjectName("le_old_pwd")
        self.label = QtWidgets.QLabel(Change_pwd_dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 60, 16))
        self.label.setObjectName("label")
        self.le_new_pwd = QtWidgets.QLineEdit(Change_pwd_dialog)
        self.le_new_pwd.setGeometry(QtCore.QRect(110, 80, 161, 31))
        self.le_new_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.le_new_pwd.setText("")
        self.le_new_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_new_pwd.setObjectName("le_new_pwd")
        self.label_2 = QtWidgets.QLabel(Change_pwd_dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Change_pwd_dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 71, 20))
        self.label_3.setObjectName("label_3")
        self.le_confirm_pwd = QtWidgets.QLineEdit(Change_pwd_dialog)
        self.le_confirm_pwd.setGeometry(QtCore.QRect(110, 130, 161, 31))
        self.le_confirm_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.le_confirm_pwd.setText("")
        self.le_confirm_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_confirm_pwd.setObjectName("le_confirm_pwd")

        self.retranslateUi(Change_pwd_dialog)
        self.buttonBox.accepted.connect(Change_pwd_dialog.accept)
        self.buttonBox.rejected.connect(Change_pwd_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Change_pwd_dialog)

    def retranslateUi(self, Change_pwd_dialog):
        _translate = QtCore.QCoreApplication.translate
        Change_pwd_dialog.setWindowTitle(_translate("Change_pwd_dialog", "Dialog"))
        self.label.setText(_translate("Change_pwd_dialog", "旧密码："))
        self.label_2.setText(_translate("Change_pwd_dialog", "新密码："))
        self.label_3.setText(_translate("Change_pwd_dialog", "确认密码："))
