# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(266, 298)
        self.buttonBox = QtWidgets.QDialogButtonBox(RegisterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 240, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(RegisterDialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(RegisterDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RegisterDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(RegisterDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 60, 16))
        self.label_4.setObjectName("label_4")
        self.le_reg_username = QtWidgets.QLineEdit(RegisterDialog)
        self.le_reg_username.setGeometry(QtCore.QRect(90, 40, 161, 31))
        self.le_reg_username.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_username.setText("")
        self.le_reg_username.setObjectName("le_reg_username")
        self.le_reg_password = QtWidgets.QLineEdit(RegisterDialog)
        self.le_reg_password.setGeometry(QtCore.QRect(90, 90, 161, 31))
        self.le_reg_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.le_reg_password.setText("")
        self.le_reg_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_reg_password.setObjectName("le_reg_password")
        self.le_reg_studentid = QtWidgets.QLineEdit(RegisterDialog)
        self.le_reg_studentid.setGeometry(QtCore.QRect(90, 140, 161, 31))
        self.le_reg_studentid.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_studentid.setText("")
        self.le_reg_studentid.setObjectName("le_reg_studentid")
        self.le_reg_realname = QtWidgets.QLineEdit(RegisterDialog)
        self.le_reg_realname.setGeometry(QtCore.QRect(90, 190, 161, 31))
        self.le_reg_realname.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_realname.setText("")
        self.le_reg_realname.setObjectName("le_reg_realname")

        self.retranslateUi(RegisterDialog)
        self.buttonBox.accepted.connect(RegisterDialog.accept)
        self.buttonBox.rejected.connect(RegisterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Dialog"))
        self.label.setText(_translate("RegisterDialog", "用户名："))
        self.label_2.setText(_translate("RegisterDialog", "密码："))
        self.label_3.setText(_translate("RegisterDialog", "学号："))
        self.label_4.setText(_translate("RegisterDialog", "真实姓名："))
