# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(281, 321)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 60, 16))
        self.label_4.setObjectName("label_4")
        self.le_reg_username = QtWidgets.QLineEdit(self.centralwidget)
        self.le_reg_username.setGeometry(QtCore.QRect(100, 10, 161, 31))
        self.le_reg_username.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_username.setObjectName("le_reg_username")
        self.le_reg_password = QtWidgets.QLineEdit(self.centralwidget)
        self.le_reg_password.setGeometry(QtCore.QRect(100, 60, 161, 31))
        self.le_reg_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.le_reg_password.setText("")
        self.le_reg_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_reg_password.setObjectName("le_reg_password")
        self.le_reg_studentid = QtWidgets.QLineEdit(self.centralwidget)
        self.le_reg_studentid.setGeometry(QtCore.QRect(100, 110, 161, 31))
        self.le_reg_studentid.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_studentid.setText("")
        self.le_reg_studentid.setObjectName("le_reg_studentid")
        self.le_reg_realname = QtWidgets.QLineEdit(self.centralwidget)
        self.le_reg_realname.setGeometry(QtCore.QRect(100, 160, 161, 31))
        self.le_reg_realname.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.le_reg_realname.setText("")
        self.le_reg_realname.setObjectName("le_reg_realname")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 60, 16))
        self.label_3.setObjectName("label_3")
        self.pb_reg_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pb_reg_ok.setGeometry(QtCore.QRect(192, 220, 81, 31))
        self.pb_reg_ok.setObjectName("pb_reg_ok")
        self.pb_reg_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pb_reg_cancel.setGeometry(QtCore.QRect(110, 220, 81, 31))
        self.pb_reg_cancel.setObjectName("pb_reg_cancel")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 24))
        self.menubar.setObjectName("menubar")
        RegisterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.label.setText(_translate("RegisterWindow", "用户名："))
        self.label_2.setText(_translate("RegisterWindow", "密码："))
        self.label_4.setText(_translate("RegisterWindow", "真实姓名："))
        self.le_reg_username.setText(_translate("RegisterWindow", "登录用的用户名"))
        self.label_3.setText(_translate("RegisterWindow", "学号："))
        self.pb_reg_ok.setText(_translate("RegisterWindow", "OK"))
        self.pb_reg_cancel.setText(_translate("RegisterWindow", "OK"))
