# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sunhaiyang/PycharmProjects/pyqt5/lesson9/gridLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridMainWindow(object):
    def setupUi(self, GridMainWindow):
        GridMainWindow.setObjectName("GridMainWindow")
        GridMainWindow.resize(438, 312)
        self.centralwidget = QtWidgets.QWidget(GridMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 9, 401, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        GridMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GridMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 438, 24))
        self.menubar.setObjectName("menubar")
        GridMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GridMainWindow)
        self.statusbar.setObjectName("statusbar")
        GridMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GridMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GridMainWindow)

    def retranslateUi(self, GridMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GridMainWindow.setWindowTitle(_translate("GridMainWindow", "MainWindow"))
        self.label.setText(_translate("GridMainWindow", "密码"))
        self.pushButton.setText(_translate("GridMainWindow", "确定"))
        self.label_2.setText(_translate("GridMainWindow", "用户名"))
        self.pushButton_2.setText(_translate("GridMainWindow", "取消"))
